Repository foxglove/studio, pull requests merged in 2021-07, with the labels that each got.

#1361 Add testMatch to jest config to avoid running tests in studio-base/dist
  packages/studio-base/jest.config.json
Labels: devx

#1355 Use fuzzy time parsing in PlaybackTimeDisplayMethod
  packages/studio-base/src/util/formatTime.ts
  packages/studio-base/src/util/parseFuzzyRosTime.test.ts
  packages/studio-base/src/util/parseFuzzyRosTime.ts
  packages/studio-base/src/util/time.test.ts
  packages/studio-base/src/util/time.ts
Labels: customer request, ux

#1398 Hover and click to seek in Map panel
  packages/studio-base/src/components/PanelExtensionAdapter.tsx
  packages/studio-base/src/panels/Map/FilteredPointMarkers.tsx
  packages/studio-base/src/panels/Map/MapPanel.tsx
  packages/studio/index.d.ts
Labels: customer request, docs, feature, panel: map

#1367 Feature: Render image panel canvas at screen resolution
  packages/studio-base/package.json
  packages/studio-base/src/PanelAPI/README.md
  packages/studio-base/src/PanelAPI/useMessageReducer.ts
  packages/studio-base/src/panels/ImageView/ImageCanvas.module.scss
  packages/studio-base/src/panels/ImageView/ImageCanvas.stories.tsx
  packages/studio-base/src/panels/ImageView/ImageCanvas.tsx
  packages/studio-base/src/panels/ImageView/ImageCanvas.worker.ts
  packages/studio-base/src/panels/ImageView/PinholeCameraModel.ts
  packages/studio-base/src/panels/ImageView/index.help.md
  packages/studio-base/src/panels/ImageView/index.module.scss
  packages/studio-base/src/panels/ImageView/index.stories.tsx
  packages/studio-base/src/panels/ImageView/index.tsx
  packages/studio-base/src/panels/ImageView/renderImage.ts
  packages/studio-base/src/panels/ImageView/util.test.ts
  packages/studio-base/src/panels/ImageView/util.ts
  yarn.lock
Labels: docs

#1440 Topic Graph: add setting to hide topics without subscribers
  packages/studio-base/src/panels/TopicGraph/index.stories.tsx
  packages/studio-base/src/panels/TopicGraph/index.tsx
Labels: docs

#1477 Add all relevant topic visibility settings in Topic Graph panel
  packages/studio-base/src/components/ExpandingToolbar.tsx
  packages/studio-base/src/panels/TopicGraph/index.stories.tsx
  packages/studio-base/src/panels/TopicGraph/index.tsx
  packages/studio-base/src/styles/colors.module.scss
Labels: docs

#1502 Add banner for unsupported browsers + outdated Chrome versions
  web/src/Root.tsx
  web/src/VersionBanner.tsx
  web/src/index.tsx
Labels: docs

#1512 Update cross-browser github issue link
  web/src/VersionBanner.tsx
Labels: docs

#1523 studio-base package is public
  packages/studio-base/package.json
Labels: docs
