Repository foxglove/studio, pull requests merged in 2021-12, with the labels that each got.

#2342 Remove feature flag for WebSocket data source
  desktop/renderer/Root.tsx
  packages/studio-base/src/AppSetting.ts
  packages/studio-base/src/components/ExperimentalFeatureSettings.tsx
  web/src/Root.tsx
Labels: docs

#2295 Add Open Dialog feature flag
  packages/studio-base/src/AppSetting.ts
  packages/studio-base/src/Workspace.tsx
  packages/studio-base/src/components/ConnectionList/DataSourceInfo.tsx
  packages/studio-base/src/components/ConnectionList/index.tsx
  packages/studio-base/src/components/ExperimentalFeatureSettings.tsx
  packages/studio-base/src/components/LayoutBrowser/index.tsx
  packages/studio-base/src/components/OpenDialog/ActionList.tsx
  packages/studio-base/src/components/OpenDialog/Connection.tsx
  packages/studio-base/src/components/OpenDialog/OpenDialog.stories.tsx
  packages/studio-base/src/components/OpenDialog/OpenDialog.tsx
  packages/studio-base/src/components/OpenDialog/Remote.tsx
  packages/studio-base/src/components/OpenDialog/Start.tsx
  packages/studio-base/src/components/OpenDialog/View.tsx
  packages/studio-base/src/components/OpenDialog/index.ts
  packages/studio-base/src/components/OpenDialog/types.ts
  packages/studio-base/src/components/OpenDialog/useOpenFile.tsx
  packages/studio-base/src/components/PlayerManager.tsx
  packages/studio-base/src/components/Timestamp.tsx
  packages/studio-base/src/context/PlayerSelectionContext.ts
  packages/studio-base/src/dataSources/FoxgloveDataPlatformDataSourceFactory.tsx
  packages/studio-base/src/dataSources/FoxgloveWebSocketDataSourceFactory.tsx
  packages/studio-base/src/dataSources/McapLocalDataSourceFactory.ts
  packages/studio-base/src/dataSources/Ros1LocalBagDataSourceFactory.tsx
  packages/studio-base/src/dataSources/Ros1RemoteBagDataSourceFactory.tsx
  packages/studio-base/src/dataSources/Ros1SocketDataSourceFactory.tsx
  packages/studio-base/src/dataSources/Ros2LocalBagDataSourceFactory.tsx
  packages/studio-base/src/dataSources/Ros2SocketDataSourceFactory.tsx
  packages/studio-base/src/dataSources/RosbridgeDataSourceFactory.tsx
  packages/studio-base/src/dataSources/UlogLocalDataSourceFactory.tsx
  packages/studio-base/src/dataSources/VelodyneDataSourceFactory.tsx
  packages/studio-base/src/hooks/useInitialDeepLinkState.ts
  packages/studio-base/src/hooks/usePrompt.tsx
  packages/studio-base/src/util/IndexedDbRecentsStore.ts
  packages/studio-base/src/util/showOpenFilePicker.tsx
  web/src/dataSources/Ros1UnavailableDataSourceFactory.tsx
  web/src/dataSources/Ros2UnavailableDataSourceFactory.tsx
  web/src/dataSources/VelodyneUnavailableDataSourceFactory.tsx
Labels: ux, ui

#2432 Enable Open Dialog feature by default
  desktop/renderer/Root.tsx
  desktop/renderer/components/NativeStorageAppConfigurationProvider.tsx
  desktop/renderer/services/NativeStorageAppConfiguration.test.ts
  desktop/renderer/services/NativeStorageAppConfiguration.ts
  web/src/Root.tsx
  web/src/components/LocalStorageAppConfigurationProvider.tsx
Labels: docs

#2446 Update native app File menu
  desktop/common/types.ts
  desktop/main/StudioWindow.ts
  packages/studio-base/src/App.tsx
  packages/studio-base/src/Workspace.tsx
  packages/studio-base/src/components/NativeFileMenuPlayerSelection.tsx
  packages/studio-base/src/components/OpenDialog/Connection.tsx
  packages/studio-base/src/components/OpenDialog/OpenDialog.tsx
  packages/studio-base/src/components/OpenDialog/index.ts
  packages/studio-base/src/context/NativeAppMenuContext.ts
Labels: release blocker

#2490 Remove support for LinedConvexHulls
  packages/@types/quickhull3d/index.d.ts
  packages/@types/quickhull3d/package.json
  packages/studio-base/package.json
  packages/studio-base/src/panels/ThreeDimensionalViz/GridBuilder.stories.tsx
  packages/studio-base/src/panels/ThreeDimensionalViz/SceneBuilder/index.ts
  packages/studio-base/src/panels/ThreeDimensionalViz/TopicSettingsEditor/MarkerSettingsEditor.tsx
  packages/studio-base/src/panels/ThreeDimensionalViz/World.tsx
  packages/studio-base/src/panels/ThreeDimensionalViz/WorldMarkers.tsx
  packages/studio-base/src/panels/ThreeDimensionalViz/commands/LinedConvexHulls.tsx
  packages/studio-base/src/panels/ThreeDimensionalViz/commands/index.ts
  packages/studio-base/src/panels/ThreeDimensionalViz/types.ts
  yarn.lock
Labels: ux, docs

#2526 Remove ROS_HOSTNAME from app settings
  packages/studio-base/src/AppSetting.ts
  packages/studio-base/src/components/Preferences.tsx
Labels: docs
