Repository foxglove/studio, pull requests merged in 2021-11, with the labels that each got.

#1513 Move Player creation out of PlayerManager
  desktop/renderer/Root.tsx
  packages/studio-base/src/App.tsx
  packages/studio-base/src/Workspace.tsx
  packages/studio-base/src/components/ConnectionList/index.tsx
  packages/studio-base/src/components/NativeFileMenuPlayerSelection.tsx
  packages/studio-base/src/components/PlayerManager.tsx
  packages/studio-base/src/context/PlayerSelectionContext.ts
  packages/studio-base/src/dataSources/FoxgloveDataPlatformDataSourceFactory.tsx
  packages/studio-base/src/dataSources/Ros1LocalBagDataSourceFactory.tsx
  packages/studio-base/src/dataSources/Ros1RemoteBagDataSourceFactory.tsx
  packages/studio-base/src/dataSources/Ros1SocketDataSourceFactory.tsx
  packages/studio-base/src/dataSources/Ros2LocalBagDataSourceFactory.tsx
  packages/studio-base/src/dataSources/Ros2SocketDataSourceFactory.tsx
  packages/studio-base/src/dataSources/RosbridgeDataSourceFactory.tsx
  packages/studio-base/src/dataSources/VelodyneDataSourceFactory.tsx
  packages/studio-base/src/hooks/usePrompt.tsx
  packages/studio-base/src/index.ts
  packages/studio-base/src/players/AnalyticsMetricsCollector.ts
  packages/studio-base/src/players/buildPlayer.ts
  web/src/Root.tsx
  web/src/dataSources/Ros1UnavailableDataSourceFactory.tsx
  web/src/dataSources/Ros2UnavailableDataSourceFactory.tsx
  web/src/dataSources/VelodyneUnavailableDataSourceFactory.tsx
Labels: tech debt

#2087 Remove other source method from Raw Message panel
  packages/studio-base/src/panels/RawMessages/fixture.ts
  packages/studio-base/src/panels/RawMessages/index.stories.tsx
  packages/studio-base/src/panels/RawMessages/index.tsx
Labels: docs

#2105 Enable field matching by default
  packages/studio-base/src/AppSetting.ts
  packages/studio-base/src/components/ExperimentalFeatureSettings.tsx
  packages/studio-base/src/components/MessagePathSyntax/MessagePathInput.tsx
Labels: docs

#2112 Add Turbo colormap in addition to Rainbow for point clouds
  packages/studio-base/src/panels/ThreeDimensionalViz/TopicSettingsEditor/PointCloudSettingsEditor.tsx
  packages/studio-base/src/panels/ThreeDimensionalViz/TopicSettingsEditor/turboColor.ts
  packages/studio-base/src/panels/ThreeDimensionalViz/commands/PointClouds/decodeMarker.ts
  packages/studio-base/src/panels/ThreeDimensionalViz/commands/PointClouds/index.tsx
Labels: docs

#2161 Add enter/exit fullscreen icon to panel toolbar
  packages/studio-base/src/components/MockPanelContextProvider.tsx
  packages/studio-base/src/components/Panel.tsx
  packages/studio-base/src/components/PanelContext.ts
  packages/studio-base/src/components/PanelToolbar/index.stories.tsx
  packages/studio-base/src/components/PanelToolbar/index.tsx
  packages/studio-base/src/panels/PlaybackPerformance/index.stories.tsx
Labels: docs, SS

#2154 Pass ROS parameters to extension panels.
  packages/studio-base/src/PanelAPI/useParameter.ts
  packages/studio-base/src/components/MessagePipeline/FakePlayer.ts
  packages/studio-base/src/components/MessagePipeline/MockMessagePipelineProvider.tsx
  packages/studio-base/src/components/MessagePipeline/index.tsx
  packages/studio-base/src/components/PanelExtensionAdapter.stories.tsx
  packages/studio-base/src/components/PanelExtensionAdapter.tsx
  packages/studio-base/src/panels/Parameters/index.stories.tsx
  packages/studio-base/src/panels/Parameters/index.tsx
  packages/studio-base/src/players/FoxgloveDataPlatformPlayer/index.ts
  packages/studio-base/src/players/OrderedStampPlayer.ts
  packages/studio-base/src/players/RandomAccessPlayer.ts
  packages/studio-base/src/players/Ros1Player.ts
  packages/studio-base/src/players/Ros2Player.ts
  packages/studio-base/src/players/RosbridgePlayer.ts
  packages/studio-base/src/players/UserNodePlayer/index.ts
  packages/studio-base/src/players/VelodynePlayer.ts
  packages/studio-base/src/players/types.ts
  packages/studio-base/src/randomAccessDataProviders/UlogDataProvider.ts
  packages/studio-base/src/randomAccessDataProviders/types.ts
  packages/studio/index.d.ts
Labels: feature, docs
