Repository foxglove/studio, pull requests merged in 2022-07, with the labels that each got.

#3767 Fix erroreneous "&:" causing body background to have hover state
  packages/studio-base/src/components/CssBaseline.tsx
Labels: bug

#3868 Move FoxgloveStack to use TSS-react instead of muiStyled
  packages/studio-base/package.json
  packages/studio-base/src/components/Sidebar/SidebarButton.tsx
  packages/studio-base/src/components/Stack.tsx
  yarn.lock
Labels: performance

#3883 Rename Node Playground to User Scripts
  packages/studio-base/src/panels/NodePlayground/Editor.tsx
  packages/studio-base/src/panels/NodePlayground/Sidebar.tsx
  packages/studio-base/src/panels/NodePlayground/index.help.md
  packages/studio-base/src/panels/NodePlayground/index.stories.tsx
  packages/studio-base/src/panels/NodePlayground/index.tsx
  packages/studio-base/src/panels/NodePlayground/playground-icon.svg
  packages/studio-base/src/panels/index.ts
  packages/studio-base/src/players/UserNodePlayer/index.test.ts
  packages/studio-base/src/players/UserNodePlayer/index.ts
  packages/studio-base/src/players/UserNodePlayer/nodeRuntimeWorker/index.ts
  packages/studio-base/src/players/UserNodePlayer/nodeRuntimeWorker/registry.ts
  packages/studio-base/src/players/UserNodePlayer/nodeTransformerWorker/__snapshots__/generateRosLib.test.ts.snap
  packages/studio-base/src/players/UserNodePlayer/nodeTransformerWorker/generateRosLib.test.ts
  packages/studio-base/src/players/UserNodePlayer/nodeTransformerWorker/generateRosLib.ts
  packages/studio-base/src/players/UserNodePlayer/nodeTransformerWorker/generateTypesLib.test.ts
  packages/studio-base/src/players/UserNodePlayer/nodeTransformerWorker/index.ts
  packages/studio-base/src/players/UserNodePlayer/nodeTransformerWorker/transform.test.ts
  packages/studio-base/src/players/UserNodePlayer/nodeTransformerWorker/transform.ts
  packages/studio-base/src/players/UserNodePlayer/nodeTransformerWorker/typescript/ast.ts
  packages/studio-base/src/players/UserNodePlayer/nodeTransformerWorker/typescript/lib.ts
  packages/studio-base/src/players/UserNodePlayer/nodeTransformerWorker/typescript/ros.ts
  packages/studio-base/src/players/UserNodePlayer/nodeTransformerWorker/typescript/templates/index.ts
  packages/studio-base/src/players/UserNodePlayer/nodeTransformerWorker/typescript/templates/locationFix.ts.template
  packages/studio-base/src/players/UserNodePlayer/nodeTransformerWorker/typescript/templates/marker.ts.template
  packages/studio-base/src/players/UserNodePlayer/nodeTransformerWorker/typescript/templates/multipleInputs.ts.template
  packages/studio-base/src/players/UserNodePlayer/nodeTransformerWorker/typescript/templates/skeleton.ts.template
  packages/studio-base/src/util/globalConstants.ts
  packages/studio-base/webpack.ts
Labels: docs
