Repository foxglove/studio, pull requests merged in 2022-05, with the labels that each got.

#3364 Add `Custom` map tile layer option to map panel
  packages/studio-base/src/panels/Map/MapPanel.tsx
Labels: docs

#3397 Add new precision attribute to number inputs
  packages/studio-base/src/components/SettingsTreeEditor/FieldEditor.tsx
  packages/studio-base/src/components/SettingsTreeEditor/index.stories.tsx
  packages/studio-base/src/components/SettingsTreeEditor/inputs/NumberInput.tsx
  packages/studio-base/src/components/SettingsTreeEditor/inputs/Vec3Input.tsx
  packages/studio-base/src/components/SettingsTreeEditor/types.ts
Labels: ui

#3395 Fix extension panel toolbar & content layout
  packages/studio-base/src/components/PanelExtensionAdapter.tsx
  packages/studio-base/src/panels/ThreeDeeRender/ThreeDeeRender.tsx
Labels: panel: map, ui, new3d

#3394 Move all settings under a top level root and clean up alignment
  packages/studio-base/src/components/SettingsTreeEditor/FieldEditor.tsx
  packages/studio-base/src/components/SettingsTreeEditor/NodeEditor.tsx
  packages/studio-base/src/components/SettingsTreeEditor/index.stories.tsx
  packages/studio-base/src/components/SettingsTreeEditor/index.tsx
  packages/studio-base/src/components/SettingsTreeEditor/types.ts
  packages/studio-base/src/panels/Image/index.tsx
  packages/studio-base/src/panels/Map/MapPanel.tsx
  packages/studio-base/src/panels/NodePlayground/index.tsx
  packages/studio-base/src/panels/Plot/index.tsx
  packages/studio-base/src/panels/Plot/settings.ts
  packages/studio-base/src/panels/Publish/index.tsx
  packages/studio-base/src/panels/RawMessages/index.tsx
  packages/studio-base/src/panels/RawMessages/settings.ts
  packages/studio-base/src/panels/ThreeDeeRender/ThreeDeeRender.tsx
  packages/studio-base/src/panels/ThreeDeeRender/settings.ts
  packages/studio-base/src/panels/ThreeDimensionalViz/index.tsx
  packages/studio-base/src/panels/ThreeDimensionalViz/settings.ts
  packages/studio-base/src/panels/VariableSlider/index.tsx
  packages/studio-base/src/panels/diagnostics/DiagnosticSummary.tsx
Labels: ui

#3388 Change Diagnostics panel names to "ROS Diagnostics"
  packages/studio-base/src/panels/diagnostics/DiagnosticStatusPanel.help.md
  packages/studio-base/src/panels/diagnostics/DiagnosticSummary.help.md
  packages/studio-base/src/panels/index.ts
Labels: docs

#3402 Adjust selected panel style
  packages/studio-base/src/components/CssBaseline.tsx
  packages/studio-base/src/components/PanelRoot.tsx
Labels: bug
