Repository foxglove/studio, pull requests merged in 2022-06, with the labels that each got.

#3390 Add error field to customTileUrl setting when invalid
  packages/studio-base/src/panels/Map/MapPanel.tsx
  packages/studio-base/src/panels/Map/config.ts
Labels: panel: map, ui

#3552 Add callService api to the panel extension interface
  packages/@types/roslib/index.d.ts
  packages/studio-base/src/components/MessagePipeline/FakePlayer.ts
  packages/studio-base/src/components/MessagePipeline/MockMessagePipelineProvider.tsx
  packages/studio-base/src/components/MessagePipeline/index.test.tsx
  packages/studio-base/src/components/MessagePipeline/index.tsx
  packages/studio-base/src/components/PanelExtensionAdapter.tsx
  packages/studio-base/src/players/FoxgloveDataPlatformPlayer/index.ts
  packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.ts
  packages/studio-base/src/players/IterablePlayer/IterablePlayer.ts
  packages/studio-base/src/players/OrderedStampPlayer.ts
  packages/studio-base/src/players/RandomAccessPlayer.ts
  packages/studio-base/src/players/Ros1Player.ts
  packages/studio-base/src/players/Ros2Player.ts
  packages/studio-base/src/players/RosbridgePlayer.ts
  packages/studio-base/src/players/UserNodePlayer/index.ts
  packages/studio-base/src/players/VelodynePlayer.ts
  packages/studio-base/src/players/types.ts
  packages/studio/index.d.ts
Labels: docs

#3607 Add didSeek to extension API
  packages/studio-base/src/components/PanelExtensionAdapter.test.tsx
  packages/studio-base/src/components/PanelExtensionAdapter.tsx
  packages/studio/index.d.ts
Labels: docs

#3372 Add subscriber options to extension api
  packages/studio-base/src/components/PanelExtensionAdapter.tsx
  packages/studio-base/src/panels/ThreeDeeRender/ThreeDeeRender.tsx
  packages/studio/index.d.ts
Labels: docs

#3680 Allow string ordering values and sort new3d topics by topic name
  packages/studio-base/src/components/SettingsTreeEditor/utils.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/Cameras.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/Images.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/Markers.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/OccupancyGrids.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/PointClouds.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/Poses.ts
  packages/studio/index.d.ts
Labels: new3d

#3681 Order new3d custom layers by creation order
  packages/studio-base/src/panels/ThreeDeeRender/renderables/Grids.ts
  packages/studio-base/src/panels/ThreeDeeRender/settings.ts
Labels: new3d

#3717 Add PanelExtensionContext.dataSourceProfile, New3D strips "/" from coordinate frames for ROS data sources
  packages/studio-base/src/components/MessagePipeline/FakePlayer.ts
  packages/studio-base/src/components/MessagePipeline/MessageOrderTracker.test.ts
  packages/studio-base/src/components/MessagePipeline/MockMessagePipelineProvider.tsx
  packages/studio-base/src/components/MessagePipeline/index.tsx
  packages/studio-base/src/components/MessagePipeline/usePlayerState.ts
  packages/studio-base/src/components/PanelExtensionAdapter.tsx
  packages/studio-base/src/components/PlaybackControls/index.stories.tsx
  packages/studio-base/src/panels/ThreeDeeRender/Renderer.ts
  packages/studio-base/src/panels/ThreeDeeRender/ThreeDeeRender.tsx
  packages/studio-base/src/panels/ThreeDeeRender/renderables/Cameras.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/Images.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/Markers.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/OccupancyGrids.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/PointCloudsAndLaserScans.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/Polygons.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/PoseArrays.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/Poses.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/TopicMarkers.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/markers/RenderableMarker.ts
  packages/studio-base/src/players/FoxgloveDataPlatformPlayer/index.ts
  packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.ts
  packages/studio-base/src/players/IterablePlayer/BagIterableSource.ts
  packages/studio-base/src/players/IterablePlayer/DataPlatformIterableSource.ts
  packages/studio-base/src/players/IterablePlayer/IIterableSource.ts
  packages/studio-base/src/players/IterablePlayer/IterablePlayer.test.ts
  packages/studio-base/src/players/IterablePlayer/IterablePlayer.ts
  packages/studio-base/src/players/IterablePlayer/Mcap/McapIndexedIterableSource.ts
  packages/studio-base/src/players/IterablePlayer/Mcap/McapIterableSource.ts
  packages/studio-base/src/players/RandomAccessPlayer.ts
  packages/studio-base/src/players/Ros1Player.ts
  packages/studio-base/src/players/Ros2Player.ts
  packages/studio-base/src/players/RosbridgePlayer.ts
  packages/studio-base/src/players/TestProvider.ts
  packages/studio-base/src/players/VelodynePlayer.ts
  packages/studio-base/src/players/types.ts
  packages/studio-base/src/randomAccessDataProviders/BagDataProvider.ts
  packages/studio-base/src/randomAccessDataProviders/Mcap0IndexedDataProvider.ts
  packages/studio-base/src/randomAccessDataProviders/Mcap0StreamedDataProvider.ts
  packages/studio-base/src/randomAccessDataProviders/McapPre0DataProvider.ts
  packages/studio-base/src/randomAccessDataProviders/MemoryDataProvider.ts
  packages/studio-base/src/randomAccessDataProviders/Ros1MemoryCacheDataProvider.test.ts
  packages/studio-base/src/randomAccessDataProviders/Rosbag2DataProvider.ts
  packages/studio-base/src/randomAccessDataProviders/UlogDataProvider.ts
  packages/studio-base/src/randomAccessDataProviders/types.ts
  packages/studio/index.d.ts
Labels: docs
