Repository foxglove/studio, pull requests merged in 2023-08, with the labels that each got.

#6538 Allow custom layer URDFs to subscribe to a topic
  packages/studio-base/src/components/SettingsTreeEditor/FieldEditor.tsx
  packages/studio-base/src/panels/ThreeDeeRender/ThreeDeeRender.tsx
  packages/studio-base/src/panels/ThreeDeeRender/renderables/Urdfs.ts
  packages/studio-base/src/panels/ThreeDeeRender/stories/UrdfDisplayMode.stories.tsx
  packages/studio-base/src/panels/ThreeDeeRender/stories/Urdfs.stories.tsx
  packages/studio/src/index.ts
Labels: docs

#6593 Allow to set URDF fallback color
  packages/studio-base/src/panels/ThreeDeeRender/renderables/Urdfs.ts
  packages/studio-base/src/panels/ThreeDeeRender/stories/UrdfDisplayMode.stories.tsx
Labels: docs

#6397 Add Font Settings for Raw Messages Panel
  packages/studio-base/src/panels/RawMessages/index.tsx
  packages/studio-base/src/panels/RawMessages/types.ts
Labels: docs, linear

#6687 Support x axis min, max and range in state transitions panel
  packages/studio-base/src/i18n/en/index.ts
  packages/studio-base/src/i18n/en/stateTransitions.ts
  packages/studio-base/src/panels/StateTransitions/index.stories.tsx
  packages/studio-base/src/panels/StateTransitions/index.tsx
  packages/studio-base/src/panels/StateTransitions/messagesToDatasets.ts
  packages/studio-base/src/panels/StateTransitions/settings.ts
  packages/studio-base/src/panels/StateTransitions/types.ts
Labels: ux, docs
