Repository foxglove/studio, pull requests merged in 2023-02, with the labels that each got.

#5296 Implement focused path in settings API
  packages/studio-base/src/components/SettingsTreeEditor/NodeEditor.tsx
  packages/studio-base/src/components/SettingsTreeEditor/index.tsx
  packages/studio-base/src/panels/Plot/NewPlotLegend.tsx
  packages/studio-base/src/panels/Plot/NewPlotLegendRow.tsx
  packages/studio-base/src/panels/Plot/index.tsx
  packages/studio-base/src/panels/Plot/settings.ts
  packages/studio/index.d.ts
Labels: ux, extensions, docs

#5287 Make new plot legend & settings the default
  packages/studio-base/src/AppSetting.ts
  packages/studio-base/src/components/ColorPicker/index.stories.tsx
  packages/studio-base/src/components/ColorPicker/index.tsx
  packages/studio-base/src/components/ExperimentalFeatureSettings.tsx
  packages/studio-base/src/panels/Plot/NewPlotLegend.tsx
  packages/studio-base/src/panels/Plot/NewPlotLegendRow.tsx
  packages/studio-base/src/panels/Plot/PathSettingsModal.stories.tsx
  packages/studio-base/src/panels/Plot/PathSettingsModal.tsx
  packages/studio-base/src/panels/Plot/PlotLegend.stories.tsx
  packages/studio-base/src/panels/Plot/PlotLegend.tsx
  packages/studio-base/src/panels/Plot/PlotLegendRow.tsx
  packages/studio-base/src/panels/Plot/index.tsx
  packages/studio-base/src/panels/Plot/settings.ts
Labels: panel: plot

#5331 Revert "Improve consistency of renderable disposing"
  packages/studio-base/src/panels/ThreeDeeRender/Renderable.ts
  packages/studio-base/src/panels/ThreeDeeRender/dispose.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/MeasurementTool.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/PublishClickTool.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/SceneEntities.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/TopicEntities.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/TopicMarkers.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/markers/RenderableCube.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/markers/RenderableCubeList.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/markers/RenderableCylinder.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/markers/RenderableLineList.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/markers/RenderableMeshResource.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/markers/RenderablePoints.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/markers/RenderableSphere.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/markers/RenderableSphereList.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/markers/RenderableTextViewFacing.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/markers/RenderableTriangleList.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/primitives/RenderableArrows.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/primitives/RenderableCubes.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/primitives/RenderableCylinders.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/primitives/RenderableLines.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/primitives/RenderableModels.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/primitives/RenderableSpheres.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/primitives/RenderableTexts.ts
  packages/studio-base/src/panels/ThreeDeeRender/renderables/primitives/RenderableTriangles.ts
Labels: release blocker

#5395 Move plot series message path above label
  packages/studio-base/src/panels/Plot/settings.ts
Labels: docs
